import type { Express, Request, Response } from "express";
import { checkTokenBudget, requireAuth } from "./auth";
import { randomUUID } from "crypto";
import { aiLimiter } from "./rateLimits";
import { getUserById, incrementTokenUsage } from "./authStorage";
import { usageLedger } from "./db";
import {
  DocumentQuotaError,
  assertDocumentCreationAllowed,
  reserveDocumentCapacity,
} from "./documentQuota";
import { projectStorage } from "./projectStorage";
import { writingStyleStorage } from "./writingStyleStorage";
import { storage } from "./storage";
import {
  runWritingPipeline,
  type WritingRequest,
  type WritingSource,
  type WritingSSEEvent,
} from "./writingPipeline";
import { sanitizeSseError, startSseHeartbeat } from "./sseUtils";
import { buildAuthorLabel, clipText } from "./chat/shared";
import type { CitationData } from "@shared/schema";
import { createLogger } from "./logger";

const logger = createLogger("writingRoutes");

const MAX_SOURCE_EXCERPT_CHARS = 700;
const MAX_SOURCE_FULLTEXT_CHARS = 7000;

function toSafeFilename(topic: string): string {
  const base = topic
    .replace(/[\\/:*?"<>|]/g, "_")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80);
  const datePart = new Date().toISOString().slice(0, 10);
  return `${base || "generated-paper"}-${datePart}.md`;
}

export async function savePaperToProject(
  projectId: string,
  topic: string,
  fullText: string,
  userId: string,
): Promise<{
  documentId: string;
  projectDocumentId: string;
  filename: string;
  savedAt: number;
}> {
  const filename = toSafeFilename(topic);
  const summary = clipText(fullText, 400);
  const reservation = await reserveDocumentCapacity(userId, Buffer.byteLength(fullText, "utf8"));
  let createdDocumentId: string | null = null;

  try {
    const createdDocument = await storage.createDocument({
      filename,
      fullText,
      summary: summary || "AI-generated paper",
      userIntent: `AI-generated paper for topic: ${topic}`,
      userId,
    });
    createdDocumentId = createdDocument.id;

    const projectDocument = await projectStorage.addDocumentToProject({
      projectId,
      documentId: createdDocument.id,
      roleInProject: "AI-generated draft",
      projectContext: `Generated by Writing pipeline on ${new Date().toISOString()}`,
    });

    return {
      documentId: createdDocument.id,
      projectDocumentId: projectDocument.id,
      filename: createdDocument.filename,
      savedAt: Date.now(),
    };
  } catch (error) {
    if (createdDocumentId) {
      await storage.deleteDocument(createdDocumentId);
    }
    await reservation.release();
    throw error;
  }
}

export function registerWritingRoutes(app: Express): void {
  // POST /api/write - Start writing pipeline, stream results via SSE
  app.post(
    "/api/write",
    requireAuth,
    aiLimiter,
    checkTokenBudget,
    async (req: Request, res: Response) => {
      let stopHeartbeat: (() => void) | null = null;
      let usageRequestId: string | null = null;

      try {
        const body = req.body as Partial<WritingRequest> & {
          sourceDocumentIds?: unknown;
          writingStyleId?: unknown;
        };

        // Validate required fields
        if (!body.topic || typeof body.topic !== "string" || body.topic.trim().length === 0) {
          return res.status(400).json({ error: "Topic is required" });
        }
        const hasSourceSelection = Array.isArray(body.sourceDocumentIds);
        const sourceDocumentIds = hasSourceSelection
          ? (body.sourceDocumentIds as unknown[]).filter(
              (id): id is string => typeof id === "string",
            )
          : undefined;

        // Load selected reusable writing style first, then fall back to project voice profile.
        let voiceProfile: string | null = null;
        if (
          body.writingStyleId !== undefined &&
          body.writingStyleId !== null &&
          body.writingStyleId !== ""
        ) {
          if (typeof body.writingStyleId !== "string") {
            return res.status(400).json({ error: "writingStyleId must be a string" });
          }
          const writingStyle = await writingStyleStorage.getWritingStyleForUser(
            body.writingStyleId,
            req.user!.userId,
          );
          if (!writingStyle) {
            return res.status(404).json({ error: "Writing style not found" });
          }
          voiceProfile = writingStyle.voiceProfile;
        }

        if (body.projectId) {
          const project = await projectStorage.getProject(body.projectId as string);
          if (!project || project.userId !== req.user!.userId) {
            return res.status(404).json({ error: "Project not found" });
          }
          if (!voiceProfile && project?.voiceProfile) {
            voiceProfile = project.voiceProfile;
          }
        }

        const request: WritingRequest = {
          topic: body.topic.trim(),
          annotationIds: Array.isArray(body.annotationIds) ? body.annotationIds : [],
          sourceDocumentIds,
          projectId: body.projectId || undefined,
          citationStyle: body.citationStyle || "chicago",
          tone: body.tone || "academic",
          targetLength: body.targetLength || "medium",
          noEnDashes: body.noEnDashes ?? false,
          deepWrite: body.deepWrite ?? false,
          voiceProfile,
          // /api/write uses the governed Sonnet default in writingPipeline.
          modelOverride: null,
        };

        const sources: WritingSource[] = [];
        const seenSourceIds = new Set<string>();
        const addSource = (source: WritingSource) => {
          if (seenSourceIds.has(source.id)) return;
          seenSourceIds.add(source.id);
          sources.push(source);
        };

        let projectDocs: Awaited<ReturnType<typeof projectStorage.getProjectDocumentsByProject>> =
          [];

        if (request.projectId) {
          projectDocs = await projectStorage.getProjectDocumentsByProject(request.projectId);
          try {
            await assertDocumentCreationAllowed(req.user!.userId);
          } catch (quotaError) {
            if (quotaError instanceof DocumentQuotaError) {
              return res.status(quotaError.status).json({ error: quotaError.message });
            }
            throw quotaError;
          }

          const selectedProjectDocs = hasSourceSelection
            ? projectDocs.filter((projectDoc) => sourceDocumentIds?.includes(projectDoc.id))
            : projectDocs;

          for (const projectDoc of selectedProjectDocs) {
            const fullDoc = await storage.getDocument(projectDoc.documentId);
            if (!fullDoc || fullDoc.userId !== req.user!.userId) continue;

            const citationData = (projectDoc.citationData as CitationData | null) || null;
            const summaryExcerpt =
              clipText(projectDoc.document.summary, MAX_SOURCE_EXCERPT_CHARS) ||
              clipText(fullDoc.fullText, MAX_SOURCE_EXCERPT_CHARS);

            addSource({
              id: projectDoc.id,
              kind: "project_document",
              title: citationData?.title || projectDoc.document.filename,
              author: buildAuthorLabel(citationData),
              excerpt: summaryExcerpt || "No summary available.",
              fullText:
                clipText(fullDoc.fullText, MAX_SOURCE_FULLTEXT_CHARS) ||
                summaryExcerpt ||
                "No source text available.",
              category: "project_source",
              note: projectDoc.roleInProject || null,
              citationData,
              documentFilename: projectDoc.document.filename,
            });
          }
        }

        // Backward compatibility: annotation-based writing requests
        if (request.annotationIds.length > 0 && request.projectId) {
          const projectDocById = new Map(
            projectDocs.map((projectDoc) => [projectDoc.id, projectDoc]),
          );

          for (const annotationId of request.annotationIds) {
            // Try project annotations first
            const projectAnnotation = await projectStorage.getProjectAnnotation(annotationId);
            if (projectAnnotation) {
              const projectDoc = projectDocById.get(projectAnnotation.projectDocumentId);
              if (!projectDoc) continue;
              const citationData = (projectDoc?.citationData as CitationData | null) || null;
              const docFilename = projectDoc?.document?.filename || "Unknown Source";

              addSource({
                id: projectAnnotation.id,
                kind: "annotation",
                title: citationData?.title || docFilename,
                author: buildAuthorLabel(citationData),
                excerpt: clipText(projectAnnotation.highlightedText, MAX_SOURCE_EXCERPT_CHARS),
                fullText: clipText(
                  `${projectAnnotation.highlightedText}\n${projectAnnotation.note ?? ""}`,
                  MAX_SOURCE_FULLTEXT_CHARS,
                ),
                category: projectAnnotation.category,
                note: projectAnnotation.note,
                citationData,
                documentFilename: docFilename,
              });
              continue;
            }

            // Fall back to legacy annotations
            const legacyAnnotation = await storage.getAnnotation(annotationId);
            if (legacyAnnotation) {
              const doc = await storage.getDocument(legacyAnnotation.documentId);
              if (!doc || doc.userId !== req.user!.userId) continue;
              addSource({
                id: legacyAnnotation.id,
                kind: "annotation",
                title: doc?.filename || "Legacy Source",
                author: "Unknown Author",
                excerpt: clipText(legacyAnnotation.highlightedText, MAX_SOURCE_EXCERPT_CHARS),
                fullText: clipText(
                  `${legacyAnnotation.highlightedText}\n${legacyAnnotation.note ?? ""}`,
                  MAX_SOURCE_FULLTEXT_CHARS,
                ),
                category: legacyAnnotation.category,
                note: legacyAnnotation.note,
                citationData: null,
                documentFilename: doc?.filename || "Unknown Source",
              });
            }
          }
        }

        const usageUser = await getUserById(req.user!.userId);
        if (!usageUser) return res.status(401).json({ error: "Authentication required" });
        usageRequestId = `${usageUser.id}:write:${req.header("x-request-id")?.trim() || randomUUID()}`;
        const estimatedInputTokens = Math.ceil(
          (request.topic.length +
            sources.reduce((sum, source) => sum + source.fullText.length, 0)) /
            4,
        );
        const estimatedCostCents = Math.ceil(
          ((estimatedInputTokens * 3 + 8_000 * 15) / 1_000_000) * 100,
        );
        const usageReservation = usageLedger.reserve({
          userId: usageUser.id,
          requestId: usageRequestId,
          tier: usageUser.tier,
          model: "sonnet",
          estimatedCostCents,
          billingPeriodStart: usageUser.billingCycleStart,
          billingPeriodEnd: usageUser.subscriptionCurrentPeriodEnd,
        });
        if (!usageReservation.ok) {
          usageRequestId = null;
          return res.status(429).json({
            error: "AI credit allowance reached for this period",
            reason: usageReservation.reason,
          });
        }

        let aborted = false;
        let completedFullText = "";
        let tokensUsed = 0;
        let inputTokensUsed = 0;
        let outputTokensUsed = 0;

        req.on("close", () => {
          aborted = true;
        });

        stopHeartbeat = startSseHeartbeat(res, { isClosed: () => aborted });

        // Helper to send SSE events
        const sendEvent = (event: WritingSSEEvent) => {
          if (aborted || res.writableEnded) return;
          res.write(`data: ${JSON.stringify(event)}\n\n`);
        };

        // Run the pipeline
        await runWritingPipeline(request, sources, (event) => {
          if (event.type === "complete" && event.fullText) {
            completedFullText = event.fullText;
            inputTokensUsed = event.usage?.inputTokens ?? 0;
            outputTokensUsed = event.usage?.outputTokens ?? 0;
            tokensUsed = inputTokensUsed + outputTokensUsed;
          }
          if (!aborted) {
            sendEvent(event);
          }
        });

        if (tokensUsed > 0) {
          await incrementTokenUsage(req.user!.userId, tokensUsed);
        }
        if (usageRequestId) {
          if (tokensUsed > 0) {
            const actualCostCents = Math.ceil(
              ((inputTokensUsed * 3 + outputTokensUsed * 15) / 1_000_000) * 100,
            );
            usageLedger.settle(usageRequestId, actualCostCents);
          } else {
            usageLedger.refund(usageRequestId);
          }
          usageRequestId = null;
        }

        if (!aborted && completedFullText && request.projectId) {
          try {
            sendEvent({
              type: "status",
              phase: "saving",
              message: "Saving generated paper to the project...",
            });
            const savedPaper = await savePaperToProject(
              request.projectId,
              request.topic,
              completedFullText,
              req.user!.userId,
            );
            sendEvent({
              type: "saved",
              message: `Saved to project as ${savedPaper.filename}`,
              savedPaper,
            });
          } catch (saveError) {
            logger.error({ err: saveError }, "Failed to save generated paper:");
            sendEvent({
              type: "status",
              phase: "complete",
              message:
                saveError instanceof DocumentQuotaError
                  ? `Paper generated, but it could not be saved: ${saveError.message}.`
                  : "Paper generated, but it could not be saved to the project.",
            });
          }
        }

        // End the stream
        stopHeartbeat?.();
        if (!aborted) {
          res.write("data: [DONE]\n\n");
          res.end();
        }
      } catch (error) {
        if (usageRequestId) usageLedger.refund(usageRequestId);
        logger.error({ err: error }, "Writing pipeline error:");
        stopHeartbeat?.();
        // If headers haven't been sent yet, send a JSON error
        if (!res.headersSent) {
          res.status(500).json({
            error: sanitizeSseError(error, "Writing pipeline failed"),
          });
        } else {
          // Headers already sent (SSE mode), send error event
          const errorEvent: WritingSSEEvent = {
            type: "error",
            error: sanitizeSseError(error, "Writing pipeline failed"),
          };
          res.write(`data: ${JSON.stringify(errorEvent)}\n\n`);
          res.end();
        }
      }
    },
  );

  // GET /api/write/history - Placeholder for future writing session history
  app.get("/api/write/history", requireAuth, async (_req: Request, res: Response) => {
    // Future: return list of previous writing sessions
    res.json([]);
  });
}
